# Lunar Lander Deep-q network

In [1]:
import gym
import numpy as np
import tensorflow as tf

env = gym.make("LunarLander-v2")

In [2]:
from collections import deque

class Memory:
    def __init__(self, size, samplesize):
        self.samplesize = samplesize
        self.memory = deque(maxlen=size)
        self.size = size
    
    def remember(self, experience):
        self.memory.append(experience)
    
    def sample(self):
        indecies = np.random.choice(np.arange(self.size), size=self.samplesize, replace = False)
        return [self.memory[index] for index in indecies]       
        

In [12]:
class Agent_q():
    def __init__(self, state_dim, action_dim):
        print(state_dim)
        print(action_dim)
        
        self.input = tf.placeholder(tf.float32,[None, state_dim])
        self.layer_1 = tf.contrib.layers.fully_connected(self.input, 128)
        self.layer_2 = tf.contrib.layers.fully_connected(self.layer_1, 64)
        self.output = tf.contrib.layers.fully_connected(self.layer_2, action_dim)
        
    def predict(self, state):
        feed_dict = {self.input : np.array([state])}
        q_vector = sess.run(self.output, feed_dict = feed_dict)
        return np.argmax(q_vector)

In [13]:
state = env.reset()
memory = Memory(100,10)
agent = Agent_q(env.observation_space.shape[0], env.action_space.n)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for epoch in range(0,10):
        done = False
        state = env.reset()
        while not done:
            action = agent.predict(state)
            next_state, reward, done, _ = env.step(action)
            memory.remember((state, action, reward, next_state))
            env.render()
            if done:
                break
            else:
                state = next_state
    env.close()

8
4
[[0.04972082 0.         0.10223646 0.08352432]]
[[0.05231125 0.         0.09504673 0.0842605 ]]
[[0.05485971 0.         0.08746199 0.08540273]]
[[0.05429766 0.         0.08856381 0.08351476]]
[[0.05652786 0.         0.08189403 0.08391973]]
[[0.0516152  0.         0.0886971  0.08454406]]
[[0.05273334 0.         0.08564249 0.08536639]]
[[0.05274411 0.         0.08495548 0.08359985]]
[[0.05472897 0.         0.07939596 0.08462092]]
[[0.04861046 0.         0.08656668 0.08598627]]
[[0.05022787 0.         0.08135689 0.08546343]]
[[0.04331705 0.         0.0872535  0.08626433]]
[[0.04589894 0.         0.07908236 0.08492765]]
[[0.03935062 0.         0.08377677 0.08481871]]
[[0.03278074 0.         0.08891194 0.08324369]]
[[0.03405926 0.         0.08584052 0.08314411]]
[[0.03460461 0.         0.0849939  0.08319374]]
[[0.03687219 0.         0.0802829  0.08477029]]
[[0.02952674 0.         0.08595657 0.08385906]]
[[0.03065401 0.         0.08349247 0.08370937]]
[[0.02276155 0.         0.0880083  0

[[0.         0.         0.35488522 0.60730755]]
[[0.         0.         0.36480713 0.62294364]]
[[0.         0.         0.37504995 0.6386212 ]]
[[0.         0.         0.38387525 0.65559113]]
[[0.        0.        0.3946033 0.672948 ]]
[[0.        0.        0.4064627 0.6906408]]
[[0.         0.         0.41889063 0.70787466]]
[[0.         0.         0.43194455 0.72585523]]
[[0.         0.         0.44537738 0.7443304 ]]
[[0.         0.         0.47298253 0.71695113]]
[[0.05205905 0.         0.12243368 0.08459149]]
[[0.05401963 0.         0.11859838 0.08695659]]
[[0.05531849 0.         0.11564003 0.08849642]]
[[0.05789032 0.         0.10937843 0.09076808]]
[[0.05791361 0.         0.10849927 0.0894841 ]]
[[0.05907941 0.         0.10468654 0.08900681]]
[[0.0612176  0.         0.09826833 0.08917546]]
[[0.06242568 0.         0.09601189 0.09082852]]
[[0.06441504 0.         0.09125545 0.09248227]]
[[0.05888009 0.         0.09649147 0.09370649]]
[[0.06151766 0.         0.08834185 0.09283161]]


KeyboardInterrupt: 